### ISSUE TITLE
Two suggestions: use command keys, check for existence of fonts

### ISSUE THREAD

**Issue by nobiot** [ashton314/emacs-writer#1]
@ashton314 
Love the idea. I also use Emacs for prose writing (apart from coding Elisp). I feel that this avenue you are treading is under-explored and I would love to see how your approach (and rougier's) will evolve.

I was not sure if you wished to see suggestions coming as an "Issue"; if this is not appropriate, I apologize.

Two humble suggestions, if you would like others to use `emacs-writer`.

## 1.  Use command keys for Quick Links
This format works even for Org Mode (it's a discovery for me, thanks to trying your scratch buffer. Thank you).
```
Paste .................. \\[yank]
``` 

This way, when CUA Mode is on, "Paste" (and others) will show  the correct keybinding (see an image from my scratch buffer below).

![image](https://user-images.githubusercontent.com/12507865/109381373-62292780-78da-11eb-8162-4a55a0fdd3f9.png)

## 2. Use `(x-list-fonts font)` for font existence check

I do not believe Fira Mono is common for non-programmers.
`x-list-fonts` can be used to check existence of a font. The idea is taken from the resource linked below.
It might be a good idea to put a check. If a font does not exist in the computer, I believe `writer_entry.el` will fail and may discourage non-technical users.

Source: https://github.com/kjhealy/emacs-starter-kit/blob/master/init.el#L44-L66

**Comment by yilinwei** [comment]
:+1: For `Fira Mono` not being common for non-programmers. I generally prefer a non-monospaced font for writing because I like it to look like the dead-tree variety.

**Comment by ashton314** [comment]
This is great stuff, guys! Thank you so much!

**Comment by ashton314** [comment]
@nobiot Fantastic tip with the `x-font-list`. I think I've got it so that you don't have to have a particular font installed. I'd like to expand the list of "nice" fonts before I consider this ticket closed, but if you guys wouldn't mind checking out the changes I've made so far. Thank you!

**Comment by nobiot** [comment]
@ashton314 
Yes, the problem of the font has disappeared.

There is one issue I noticed. I think this is with Straight, not with Amethyst.
On Windows, I fail to run "make"; see screen shot below.

I have made a copy of my config folder, and run `emacs -q -l ~/amethyst.el`.
Straight works automatically, and it seems to display the amethyst's initial screen as expected.
Org Mode works, so I guess there is no real problem.

![image](https://user-images.githubusercontent.com/12507865/110825531-6ff48a80-8294-11eb-8126-1abab640410f.png)

But you get this warning every time you launch Emacs (in terminal , with -l "~/amethyst.el). This would be "scary" for non-technical folks on Windows. And you would not have `make` and other UNIX toolings (I do via some geeky way called Scoop)

I have no idea how you could address this... Just FYI. Please disregard this if Windows is not your target platform.

**Comment by ashton314** [comment]
This is great to know—this might be a bit tricky for me to replicate and fix because I don’t use Windows. Maybe I can do something to suppress that error better though.

If you happen to find a solution, please let me know!

**Comment by novoid** [comment]
I can confirm that the font issue is gone.

However, if I'm using `emacs -q -l amethyst.el`, my `~/.emacs.d/` gets spammed at least with `straight/`. I aborted the setup process before it interferes with my usual emacs. You might want to add a comment in the README that `-q -l` does not avoid config directory corruption.

**Comment by ashton314** [comment]
AFAIK, `~/.emacs.d/straight` is the only file that should get created. I’ll add a comment about that in the README though.

**Comment by nobiot** [comment]
Right, this does not co-exist with your existing set up. I'd suggest to copy and rename existing config directory as a backup, and start with an empty one.

**Comment by novoid** [comment]
Since I do not use straight myself yet, if this is the only thing added to `~/.emacs.d/` this ought to be fine to me. However, if somebody who is already using straight herself/himself, the README should contain a warning IMHO.
