### ISSUE TITLE
Don't use the `*scratch*` buffer for the splash screen.

### ISSUE THREAD

**Issue by yilinwei** [ashton314/emacs-writer#2]
Taking a quick glance over your code, you have a hack around which is meant to wait until the scratch buffer is [loaded](https://github.com/ashton314/emacs-writer/commit/8ee2cf7922a2ab2e0b58638675edd790c26b0582). This is because the scratch buffer isn't really meant for a custom splash screen; there's an easier way to do that for more fine-grained control.

Here is a snippet of code which you can copy and paste into your `init.el` to illustrate how to use the variable.

```elisp
(defvar my-splash-buffer (get-buffer-create "*my splash*"))

(defun my-splash-screen ()
  (interactive)
  ;; `with-current-buffer` means everything inside
  ;; the block happens inside `my-splash-buffer`
  (with-current-buffer my-splash-buffer
    ;; We enter a nice message :)
    (insert "Hello")
    (newline)
    (insert "World")
    (newline)
    ;; Moves it back up to the start, no kludge needed!
    (goto-char (point-min))
    ;; Usually we inherit from `special-mode`, but anything is fine. Setting it to `read-only` is probably useful here though.
    (special-mode)
    ;; We return the my-splash-buffer for the next part
    (current-buffer)))

;; Switch the users to startup using it - the #' means we point
;; towards the appropriate function
(setq initial-buffer-choice #'my-splash-screen)
```

The relevant docs can be found using the web [here](http://www.gnu.org/software/emacs/manual/html_node/elisp/Startup-Summary.html) or using `info-lookup-symbol` , normally bound to `C-h S`, under the symbol `initial-buffer-choice`.

**Comment by ashton314** [comment]
+1 for the `initial-buffer-choice`. This looks like a great solution and I'll give it a whirl! Thanks!
