### ISSUE TITLE
Font error

### ISSUE THREAD

**Issue by niyumard** [ashton314/emacs-writer#5]
`git clone https://github.com/ashton314/emacs-writer.git`
`emacs -q -l writer_entry.el`
Here's the error I get after running these commands:
`set-face-attribute: Font not available: #<font-spec nil nil Input\ Mono nil nil nil nil nil 14.0 nil nil nil ((:name . "Input Mono 14") (:user-spec . "Input Mono 14"))>`

**Comment by niyumard** [comment]
This problem got solved after I installed the fonts, but definitely needs some action on your side.

**Comment by ashton314** [comment]
Absolutely right. There’s a comment in #1 that addresses this.

**Comment by novoid** [comment]
How am I able to install this font on Debian? I tried `sudo apt install fonts-firacode` but this does not seem to avoid the error. So I guess it's a different font that is required which I could not find via `apt-cache search fira`.

**Comment by ashton314** [comment]
Have you tried following the instructions here? https://github.com/tonsky/FiraCode/wiki/Installing

**Comment by novoid** [comment]
> Have you tried following the instructions here? https://github.com/tonsky/FiraCode/wiki/Installing

Yes, I did: `sudo apt install fonts-firacode`.
But you confirmed that I've installed the correct font. Therefore, there seems to be another issue even when the font is installed.
I even did `fc-cache -f` with no change.

**Comment by ashton314** [comment]
Sorry, I don’t run Debian, so I’m not going to be much help. Good luck!

**Comment by novoid** [comment]
FYI: With the latest fixes containing `x-font-list`, the font issue is gone. I can't tell how and why.

**Comment by ashton314** [comment]
… so, were you actually able to get Fira code installed? It might just be that you’re not seeing the bug manifest anymore. 😅

**Comment by novoid** [comment]
So far, I could not tell. I aborted the setup phase in the moment I realized that there is something going on in my normal `~/.emacs.d/` and I need to compare font specifics in order to confirm that Fira is used.
