### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by OrionRandD** [ashton314/emacs-writer#7]
Suggestion: add company-mode to the kit.
It will atract more users.
By the way, I fixed the font issue jut changing it to "Source Code Pro"
Have you seen this classic video as well?
Emacs For Writers
https://youtube.com/watch?v=FtieBc3KptU

Great job!
Congrats.

**Comment by ashton314** [comment]
Thanks for your interest in Amethyst!

> company-mode attracting more users.

I'm not sure about that. That certainly is important for developers with code completion, but for people writing prose, it's less of a sell, and would end up just getting in the way, I think.

I'm going to close this, but if you'd like to make a case for company-mode with a prose-focused starter kit, then please re-open with your reasoning. Include some hard evidence if you can. Please also make a more descriptive title than "Suggestion". Thanks!
